#! ~/.config/starship.toml

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 2000
scan_timeout = 500

# format = """
# [â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
# [â”‚](bold green)$directory$rust$package
# [â””â”€>](bold green) """

format = """
[$time on ${custom.OS}](bold white) $memory_usage$cmd_duration
$battery| \
$sudo$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$docker_context\
$aws$gcloud$openstack$azure$container$kubernetes\
$package\
$dart$deno$dotnet$elixir$elm$erlang$golang$haskell$helm$java$julia$kotlin$buf$c$cmake$cobol$lua$nim$nodejs$ocaml$perl$php$pulumi$purescript$python$rlang$red$ruby$rust$scala$swift$terraform$crystal$vlang$spack$vagrant$zig$nix_shell$conda\
$env_var\
$jobs\
$status
$shell$character"""

[custom.OS]
disabled = false
when = true
command = "echo $OS"
shell = "sh"
style = "bold 25"
format = "[$output]($style)"


[time]
style = "bold 244"
disabled = false
format = '[$time]($style)'
time_format = "%T"
utc_time_offset = "-5"

[sudo]
style = "bold 58"
symbol = "ïˆ›  "
disabled = false
allow_windows = true
format = "[$symbol]($style)"

[username]
disabled = false
style_root = "bold 58"
format = "[ïˆ›  ]($style)"

[c]
disabled = false
symbol = "î˜ "
style = "bold 206"
detect_extensions = [
	"h",
	"hh",
	"hpp",
	"H",
	"HH",
	"HPP",
	"c",
	"cc",
	"cpp",
	"C",
	"CC",
	"CPP",
	"CXX",
	"cxx",
	"hxx",
	"HXX",
]
format = "via [$symbol($name )]($style)"

# [battery]
# style = "bold green"
# unknown_symbol = "ï– "
# full_symbol = "ï•¸ "
# discharging_symbol = "ï•¸ "
# charging_symbol = "ï–„ "

[[battery.display]]
threshold = 10
style = "bold red"
discharging_symbol = "ï•¹ "
charging_symbol = "ï–… "
[[battery.display]]
threshold = 20
style = "bold red"
discharging_symbol = "ï•º "
charging_symbol = "ï–… "
[[battery.display]]
threshold = 30
style = "bold 202"
discharging_symbol = "ï•» "
charging_symbol = "ï–† "
[[battery.display]]
threshold = 40
style = "bold 214"
discharging_symbol = "ï•¼ "
charging_symbol = "ï–‡ "
[[battery.display]]
threshold = 50
style = "bold yellow"
discharging_symbol = "ï•½ "
charging_symbol = "ï–‡ "
[[battery.display]]
threshold = 60
style = "bold 190"
discharging_symbol = "ï•¾ "
charging_symbol = "ï–ˆ "
[[battery.display]]
threshold = 70
style = "bold 190"
discharging_symbol = "ï•¿ "
charging_symbol = "ï–ˆ "
[[battery.display]]
threshold = 80
style = "bold green"
discharging_symbol = "ï–€ "
charging_symbol = "ï–‰ "
[[battery.display]]
threshold = 90
style = "bold green"
discharging_symbol = "ï– "
charging_symbol = "ï–Š "
[[battery.display]]
threshold = 100
style = "bold green"
discharging_symbol = "ï•¸ "
charging_symbol = "ï–„ "


[memory_usage]
disabled = false
threshold = 85
symbol = "ï¡š "
style = "bold dimmed green"
format = "[$symbol ${ram_pct}]($style) "

[directory]
truncation_length = 5
use_os_path_sep = true
truncation_symbol = "ï¡ "

[shell]
fish_indicator = "fish"
bash_indicator = "bash"
cmd_indicator = "cmd"
powershell_indicator = "pwsh"
unknown_indicator = "mystery shell"
# style = "cyan bold"
disabled = false

[character]
success_symbol = "[ï¬Œ](bold green)"
error_symbol = "[ï¬Œ](bold red)"

# [cmd_duration]
# min_time = 1000
# show_notifications = true
# min_time_to_notify = 30_000
# format = "took [$duration]($style)"

[aws]
symbol = "îŒ½ "


# [conda]
# symbol = "ï„Œ "

# [dart]
# symbol = "î˜ "

# [directory]
# read_only = " ï ½"

# [docker_context]
# symbol = "ïŒˆ "

# [elixir]
# symbol = "î‰µ "

# [elm]
# symbol = "î˜¬ "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[git_branch]
style = "bold 164"
symbol = "ï˜ "

# [golang]
# symbol = "î˜§ "

# [hg_branch]
# symbol = "ï˜ "

# [java]
# symbol = "î‰– "

# [julia]
# symbol = "î˜¤ "

# [memory_usage]
# symbol = "ï¡š "

# [nim]
# symbol = "ïš¤ "

# [nix_shell]
# symbol = "ï‹œ "

# [nodejs]
# symbol = "îœ˜ "

[package]
symbol = "ï£– "

# [rust]
# symbol = "î¨ "

[buf]
format = "via [$symbol]($style)"

[cmake]
symbol = "ï¨¶ "
format = "via [$symbol]($style)"

[cobol]
format = "via [$symbol]($style)"

[crystal]
format = "via [$symbol]($style)"

[dart]
format = "via [$symbol]($style)"

[deno]
format = "via [$symbol]($style)"

[dotnet]
format = "[$symbol(ğŸ¯ $tfm )]($style)"

[elixir]
format = 'via [$symbol]($style)'

[elm]
format = 'via [$symbol]($style)'

[erlang]
format = 'via [$symbol]($style)'

[golang]
format = 'via [$symbol]($style)'

[helm]
format = 'via [$symbol]($style)'

[julia]
format = 'via [$symbol]($style)'

[kotlin]
format = 'via [$symbol]($style)'

[lua]
format = 'via [$symbol]($style)'

[nim]
format = 'via [$symbol]($style)'

[nodejs]
style = "bold green"
format = 'via [$symbol]($style)'

[ocaml]
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'

[perl]
format = 'via [$symbol]($style)'

[php]
format = 'via [$symbol]($style)'

[pulumi]
format = 'via [$symbol$stack]($style)'

[purescript]
format = 'via [$symbol]($style)'

[python]
format = 'via [$symbol]($style)'

[red]
format = 'via [$symbol]($style)'

[rlang]
format = 'via [$symbol]($style)'

[ruby]
format = 'via [$symbol]($style)'

[rust]
format = 'via [$symbol]($style)'

[swift]
format = 'via [$symbol]($style)'

[vagrant]
format = 'via [$symbol]($style)'

[vlang]
format = 'via [$symbol]($style)'

[zig]
format = 'via [$symbol]($style)'
