# scan_timeout =
add_newline = false
format = "$custom| $all"

[custom]
disabled = false

[custom.Windows]
os = "windows"
symbol = "ï…º  "
when = '[ "$IsOnPlatform" == "Windows" ]'
command = "echo 'Windows'"
shell = "sh" # you dont need fancy shit. we want speed.
style = "bold blue"
format = "[$symbol($output )]($style)"

[custom.Linux]
os = "linux"
symbol = "ïŒš "
when = '[ "$IsOnPlatform" == "Linux" ]'
command = "echo 'Linux'"
shell = "sh"
style = "bold blue"
format = "[$symbol($output )]($style)"

[custom.OSX]
os = "mac"
symbol = "ï”µ "
when = '[ "$IsOnPlatform" == "Darwin" ]'
command = "echo 'Mac'"
shell = "sh"
style = "bold blue"
format = "[$symbol($output )]($style)"

[custom.iOS]
os = "ios"
symbol = "ï…¹ "
when = '[ "$IsOnPlatform" == "iOS" ]'
command = "echo 'iOS'"
shell = "sh"
style = "bold blue"
format = "[$symbol($output )]($style)"

[custom.Android]
os = "android"
symbol = "ï”± "
when = '[ "$IsOnPlatform" == "Android" ]'
command = "echo 'Android'"
shell = "sh"
style = "bold blue"
format = "[$symbol($output )]($style)"

[sudo]
style = "bold green"
symbol = "ğŸ§™â€â™‚ï¸"
disabled = false
allow_windows = true


[[battery.display]]
threshold = 25
style = "bold red"


[shell]
fish_indicator = "ğŸ fish"
bash_indicator = "bash"
powershell_indicator = "pwsh"
unknown_indicator = "mystery shell"
# style = "cyan bold"
disabled = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[aws]
symbol = "îŒ½ "


[azure]
disabled = false
format = "on [$symbol($subscription)]($style) "
symbol = "ï´ƒ "
style = "blue bold"


[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[directory]
read_only = " ï ½"

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[rust]
symbol = "î¨ "
